### ISSUE TITLE
Bug - Can't delete Frequency

### ISSUE THREAD

**Issue by ghost** [Gaarnik/DimStorage#13]
Forge 10.12.2.1147
DimChest 1.2

I'm not able to backspace/delete/reset the Frequency. In my test I open the chest and tested with public and private once you set the Frequency you can change a number. I have tested closing and reopening too. But if I brake and place it does reset.

**Comment by Gaarnik** [comment]
I've fixed this bug thank You for your report !

**Comment by ghost** [comment]
Thank you
