### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by ghost** [Gaarnik/DimStorage#16]
DimStorage-1.7.2-1.2
forge-1.7.2-10.12.2.1147-universal

With updating my home server with MinStorage it crashed. Crash report below.

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 7/1/14 2:56 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.InstantiationException
    at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:76)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:491)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:313)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:114)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:670)
Caused by: java.lang.InstantiationException
    at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at java.lang.Class.newInstance(Class.java:374)
    at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59)
    ... 27 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Linux (amd64) version 2.6.32-431.el6.x86_64
    Java Version: 1.7.0_55, Oracle Corporation
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 164603312 bytes (156 MB) / 661651456 bytes (631 MB) up to 3262119936 bytes (3111 MB)
    JVM Flags: 1 total; -Xmx3500M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.03 FML v7.2.217.1147 Minecraft Forge 10.12.2.1147 73 mods loaded, 73 mods active
    mcp{9.03} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
    FML{7.2.217.1147} [Forge Mod Loader](ForgeMod.jar) Unloaded->Constructed
    Forge{10.12.2.1147} [Minecraft Forge](ForgeMod.jar) Unloaded->Constructed
    AppliedEnergistics2-Core{rv0-beta-35} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed
    CodeChickenCore{1.0.0} [CodeChicken Core](minecraft.jar) Unloaded->Constructed
    MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks](minecraft.jar) Unloaded->Constructed
    MobiusCore{1.2.2} [MobiusCore](minecraft.jar) Unloaded->Constructed
    OpenEye{0.6} [OpenEye](OpenEye-0.6-1.7.2.jar) Unloaded->Constructed
    TConstruct-Preloader{0.1.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed
    lucky{5.0.0} [Lucky Block]([1-7-2]_Lucky_Block_v5-0-0.jar) Unloaded->Constructed
    Baubles{1.0.0.13} [Baubles](Baubles-1.7.2-1.0.0.13.jar) Unloaded->Constructed
    Thaumcraft{4.1.1.14} [Thaumcraft](Thaumcraft-1.7.2-4.1.1.14.jar) Unloaded->Constructed
    Botania{r1.1-68} [Botania](Botania r1.1-68.jar) Unloaded->Constructed
    advancedthaumaturgy{0.1.1} [Advanced Thaumaturgy](AdvancedThaumaturgy-1.7.2-0.1.1.jar) Unloaded->Constructed
    appliedenergistics2{rv0-beta-35} [Applied Energistics 2](appliedenergistics2-rv0-beta-35.jar) Unloaded->Constructed
    BaMsGRAVE{1.4.2_01} [BaM's Grave](bamsgrave-1.7.2-1.4.2_01.jar) Unloaded->Constructed
    bdlib{1.3.0.10} [BD Lib](bdlib-mc172-1.3.0.10.jar) Unloaded->Constructed
    BiblioCraft{1.7.1} [BiblioCraft](BiblioCraft[1.7.1][MC1.7.2].jar) Unloaded->Constructed
    Mantle{1.7.2-132.45b0b50} [Mantle](Mantle-1.7.2-0.2.8.jar) Unloaded->Constructed
    Natura{2.2.0} [Natura](natura-1.7.2-2.2.0a3.jar) Unloaded->Constructed
    BiomesOPlenty{2.0.1} [Biomes O' Plenty](BiomesOPlenty-1.7.2-2.0.1.890-universal.jar) Unloaded->Constructed
    CarpentersBlocks{3.2.4} [Carpenter's Blocks](Carpenter's Blocks v3.2.4 - MC 1.7+.zip) Unloaded->Constructed
    chisel{1.5.4g} [Chisel](Chisel-1.7.2-1.5.4g.jar) Unloaded->Constructed
    ComputerCraft{1.64pr2} [ComputerCraft](ComputerCraft1.64pr2.jar) Unloaded->Constructed
    DeathCounter{3.0.1} [DeathCounter](DeathCounter-3.0.1.jar) Unloaded->Constructed
    props{1.9b} [Decocraft](DecoCraft1.7.2V1.9b.zip) Unloaded->Constructed
    dimstorage{1.2} [DimStorage](DimStorage-1.7.2-1.2.jar) Unloaded->Errored
    DungeonPack{1.7.2-2.0} [DungeonPack](DungeonPack-1.7.2-2.0.jar) Unloaded->Constructed
    eplus{1.7.2-2.0.3.1} [Enchanting Plus](EnchantingPlus-1.7.2-2.0.3.1.jar) Unloaded->Constructed
    Enchiridion{1.2} [Enchiridion](Enchiridion-1.7.2-1.1a.jar) Unloaded->Constructed
    EnderIO{2.0_beta} [Ender IO](enderio-2.0_beta.123.jar) Unloaded->Constructed
    enhancedportals{3.0.0} [EnhancedPortals](EnhancedPortals_1.7.2-universal-3.0.0b-final2.jar) Unloaded->Constructed
    extracells{2.1.1} [ExtraCells](ExtraCells-2.1.1.jar) Unloaded->Constructed
    ExtraUtilities{1.1.0b} [Extra Utilities](extrautilities-1.1.0b.jar) Unloaded->Constructed
    FinderCompass{1.7.2e} [Finder Compass](FinderCompass-1.7.2.jar) Unloaded->Constructed
    Forestry{2.4.1.27} [Forestry for Minecraft](forestry_1.7.2-2.4.1.27.jar) Unloaded->Constructed
    gendustry{1.2.0.18} [GenDustry](gendustry-mc172-1.2.0.18.jar) Unloaded->Constructed
    GraveStone{2.8.6} [GraveStone](GraveStone 2.8.6.jar) Unloaded->Constructed
    ImmibisCore{58.1.4} [Immibis Core](immibis-core-58.1.4.jar) Unloaded->Constructed
    InfernalMobs{1.5.3} [Infernal Mobs](InfernalMobs-1.7.2.jar) Unloaded->Constructed
    IronChest{6.0.14.719} [Iron Chest](ironchest-1.7.2-6.0.14.719-universal.jar) Unloaded->Constructed
    JABBA{1.1.4} [JABBA](Jabba-1.1.4.jar) Unloaded->Constructed
    Java7Checker{1.0} [Java 7 Checker](Java7Checker.jar) Unloaded->Constructed
    JASCompatability{1.0.0} [Just Another Spawner Compatibility Addon](JustAnotherSpawnerCompatibilityAddon-1.0.0.jar) Unloaded->Constructed
    LunatriusCore{1.0.2.7} [LunatriusCore](LunatriusCore-1.7.2-1.0.2.7-universal.jar) Unloaded->Constructed
    TConstruct{1.7.2-1.6.0.jenkins478} [Tinkers' Construct](TConstruct-1.7.2-1.6.0.a14.jar) Unloaded->Constructed
    Mariculture{b12} [Mariculture](Mariculture-1.7.2-b12.jar) Unloaded->Constructed
    meteors{2.12} [Falling Meteors](meteors-1.7.2-2.12.jar) Unloaded->Constructed
    Morpheus{1.7.2-1.@MINOR.14} [Morpheus](Morpheus-1.7.2-1.5.14.jar) Unloaded->Constructed
    movillages{1.1.0} [Mo' Villages](MoVillages-1.1.0.jar) Unloaded->Constructed
    MultiPageChest{1.3.1} [Multi Page Chest](MultiPageChest-1.3.1-MC1.7.2.jar) Unloaded->Constructed
    Mystcraft{0.10.15.00} [Mystcraft](mystcraft-1.7.2-0.10.15.00.jar) Unloaded->Constructed
    NetherDungeons{1.2.1} [Nether Dungeons](NetherDungeons-1.7.2-v-1.2.1.jar) Unloaded->Constructed
    MapWriter{2.1.1} [MapWriter](Opis-1.2.2a_1.7.2.jar) Unloaded->Constructed
    Opis{1.2.2a} [Opis](Opis-1.2.2a_1.7.2.jar) Unloaded->Constructed
    harvestcraft{1.7.2d} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.2e.zip) Unloaded->Constructed
    Railcraft{9.1.0.0} [Railcraft](Railcraft_1.7.2-9.1.0.0.jar) Unloaded->Constructed
    RedLogic{58.1.3} [RedLogic](redlogic-58.1.3.jar) Unloaded->Constructed
    Schematica{1.7.0.79} [Schematica](Schematica-1.7.2-1.7.0.79-universal.jar) Unloaded->Constructed
    StevesCarts{2.0.0.b15} [Steve's Carts 2](StevesCarts2.0.0.b15.jar) Unloaded->Constructed
    ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects](ThaumcraftMobAspects-1.7.2-2A.jar) Unloaded->Constructed
    ti{0.001} [Thaumic Infusion](ThaumicInfusion-0.983.jar) Unloaded->Constructed
    ThaumicTinkerer{2.4-147} [Thaumic Tinkerer](ThaumicTinkerer-2.4-147.jar) Unloaded->Constructed
    TiCTooltips{1.1.8} [TiC Tooltips](TiCTooltips-mc1.7.2-1.1.8.jar) Unloaded->Constructed
    TMechworks{1.7.2-60.0ab3ef0} [Tinkers' Mechworks](TMechworks-1.7.2-0.2.7.jar) Unloaded->Constructed
    TwilightForest{2.2.0} [The Twilight Forest](twilightforest-1.7.2-2.2.0.jar) Unloaded->Constructed
    AS_UpdateCheck{1.1.5} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.2.jar) Unloaded->Constructed
    warpbook{1.0.35} [Warp Book](warp-book-1.7.2-1.0.35.jar) Unloaded->Constructed
    yampst{1.1} [YAMPST](Yampst-Apocalypse-0.5.0.jar) Unloaded->Constructed
    bspkrsCore{6.9} [bspkrsCore]([1.7.2]bspkrsCore-universal-6.9.jar) Unloaded->Constructed
    aobd{2.0.2} [Another One Bites The Dust](AOBD-2.0.2.jar) Unloaded->Constructed
    JustAnotherSpawner{0.14.0} [Just Another Spawner](JustAnotherSpawner-0.14.5.jar) Unloaded->Constructed
    AE2 Version: beta rv0-beta-35 for Forge 10.12.0.1024
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by Gaarnik** [comment]
This bug has been reported and fixed in DimStorage 1.3
