### ISSUE TITLE
Forge

### ISSUE THREAD

**Issue by Phenix246** [Gaarnik/DimStorage#4]
Je n'arrive pas à installer les sources de forge en 1.6, pourrais tu m'envoyer les tienne que je puisse tester mon code avant de te l'envoyer

**Comment by Gaarnik** [comment]
j'étais partis avec cette base => https://drive.google.com/file/d/0B1VUTe27AtuYVGVHV1I3bjlJdTQ/edit?usp=sharing

**Comment by Phenix246** [comment]
Il serait possible d'avoir une TODO list du mod afin de voir ce que je peux faire

**Comment by Gaarnik** [comment]
Ouep je vais te faire ça au plus vite ! je vais l'ajouter à la racine du projet

**Comment by Gaarnik** [comment]
Voilà:
https://github.com/Gaarnik/DimStorage/blob/master/TODO.txt
Si tu vois des choses à ajouter à la liste hésites pas

**Comment by Phenix246** [comment]
un jenkin pout le mod , ça te tente ? je peux essayer de demander à des amis (les admins du forum MFF) d'ajouter ton mod sur le leur.

**Comment by letherman255** [comment]
Quels amis ?
