### ISSUE TITLE
Jenkin

### ISSUE THREAD

**Issue by Phenix246** [Gaarnik/DimStorage#5]
un jenkin pout le mod , ça te tente ? je peux essayer de demander à des amis (les admins du forum MFF) d'ajouter ton mod sur le jenkin de leur serveur.

**Comment by Gaarnik** [comment]
Tu veux dire quoi par un Jenkin ?

**Comment by Phenix246** [comment]
http://ci.mcnanotech.fr/
un systeme d'historique avec build intégrer, c'est très pratique, tu build depuis github l'archive est sur le serveur de jenkin, accessible à tous avec un changelogs qui permet de se rendre vers le commit qu'il décrit. par exemple pour mon mod ça donne ça : 
http://ci.mcnanotech.fr/job/Phenix246_Mod/8/

**Comment by Phenix246** [comment]
définition selon wikipedia : 
Jenkins est un outil open source d'intégration continue, fork de l'outil Hudson après les différends entre son auteur, Kohsuke Kawaguchi, et Oracle. Écrit en Java, Jenkins fonctionne dans un conteneur de servlets tel qu’Apache Tomcat, ou en mode autonome avec son propre serveur Web embarqué.

Il s'interface avec des systèmes de gestion de versions tels que CVS, Git et Subversion, et exécute des projets basés sur Apache Ant et Apache Maven aussi bien que des scripts arbitraires en shell Unix ou batch Windows.

Les générations de projets peuvent être initiées par différents moyens, tels que des mécanismes de planification similaires au cron, des systèmes de dépendances entre générations, ou par des requêtes sur certaines URL spécifiques.

**Comment by Phenix246** [comment]
Par exemple Forge utilise un système similaire

**Comment by Gaarnik** [comment]
Ha je vois se que c'est mais je suis pas sûr d'avoir le temps de l'installer et une fois installer faut maintenir une certaine présence et gérer les retours des gens tout ça

**Comment by Phenix246** [comment]
en fait c'est juste le build en ligne que je te propose, il suffit d'activer une option sur github et après jenkin fera les builds, tu n'a besoin de rien installer, le retour des gens ce fait plus par github généralement ou sur le post de présentation

**Comment by Gaarnik** [comment]
Ok bah je vais jeter un œil donc :)
